### ISSUE TITLE
Can not run the project locally with mvn azure-functions:run

### ISSUE THREAD

**Issue by uzoltan** [Microsoft/azure-maven-archetypes#30]
I'm following the guide from here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven

And installed the Azure Functions Core Tools, as seen here: 
https://imgur.com/a/xRyBjBu

I use IntelliJ's maven plugin, to package the project with mvn clean package (I have the correct working directory set), but then when trying to run the project with `azure-functions:run -X`, I get the following stacktrace:

`Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-2:run (default-cli) on project still_rca_azure_function: Azure Functions Core Tools not found. Please go to https://aka.ms/azfunc-install to install Azure Functions Core Tools first. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-2:run (default-cli) on project still_rca_azure_function: Azure Functions Core Tools not found. Please go to https://aka.ms/azfunc-install to install Azure Functions Core Tools first.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Azure Functions Core Tools not found. Please go to https://aka.ms/azfunc-install to install Azure Functions Core Tools first.
	at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:347)
	at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:293)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.Exception: Azure Functions Core Tools not found. Please go to https://aka.ms/azfunc-install to install Azure Functions Core Tools first.
	at com.microsoft.azure.maven.function.handlers.CommandHandlerImpl.handleExitValue(CommandHandlerImpl.java:103)
	at com.microsoft.azure.maven.function.handlers.CommandHandlerImpl.runCommandWithReturnCodeCheck(CommandHandlerImpl.java:39)
	at com.microsoft.azure.maven.function.RunMojo.checkRuntimeExistence(RunMojo.java:57)
	at com.microsoft.azure.maven.function.RunMojo.doExecute(RunMojo.java:43)
	at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:288)
	... 23 more`

I'm using Windows 10 Pro. What can I do? It would be nice to debug the Azure Function I want to write, before deploying it to the cloud.

**Comment by jdneo** [comment]
@uzoltan Please make sure you installed the Azure Functions Core Tools (V2) correctly. You can verify this by simply input `func` into the cmd and see if there is any output.

About how to install it, here is a reference: https://github.com/Azure/azure-functions-core-tools#windows

**Comment by uzoltan** [comment]
I did this after install, it listed all the available commands

**Comment by jdneo** [comment]
@uzoltan Ok. Then if you trigger `mvn azure-functions:run` it still throws error?

If you trigger `mvn azure-functions:run` in command line. Please make sure the `func` is in its environment variable list.

**Comment by uzoltan** [comment]
As I wrote, I used IntelliJ's maven plugin to use the run command. I can try with normal maven aswell I guess, when I'm at that PC again. How do I make sure `func` is in its environment list by the way?

**Comment by jdneo** [comment]
Emm, you can do the following:
- Open a new command line terminal
- enter `func` to see if it is available in that terminal process
- If yes, go to your function project base path
- Run `mvn azure-functions:run`

**Comment by uzoltan** [comment]
Worked with native maven, instead of the IntelliJ maven plugin, thanks.

**Comment by jdneo** [comment]
@uzoltan I guess this may because the IntelliJ is started before you installed the Azure Functions Core Tools. Then even the Azure Functions Core Tools is installed globally, the IntelliJ will not aware it exists.

You can try to close all the IntelliJ's process. Then start it again. I think then the IntelliJ's Maven plugin could work.
